version: 2
jobs:
  build:
    working_directory: ~/emoji-console # directory where steps will run
    docker:
      - image: node:8-alpine
        environment:
          NODE_ENV: test
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: before-install
          command: 'apk add ca-certificates'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: 'npm run coverage'
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
